#######################################################################################
# Book settings
title: ""
author: Daniel Bauchspiess, Rodrigo Xavier
copyright: "2021"
logo: "static/img/logo.png"
exclude_patterns: [README.md]

#######################################################################################
# Execution settings
execute:
  execute_notebooks: force
  allow_errors: true
  timeout: 500

#######################################################################################
# HTML-specific settings
html:
  favicon: "" #TODO: Preencher favicon
  use_repository_button: true
  use_issues_button: true
  google_analytics_id: "" #TODO: Preencher para poder acompanhar acessos ao site

#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine: pdflatex
  use_jupyterbook_latex: true
#  latex_documents:
#    targetname: book.tex

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface: "jupyterlab"

repository:
  url          : https://github.com/UnBeethoven/Separacao-de-Fonte-Sonora
  path_to_book : ""
  branch       : master